### ISSUE TITLE
User Guide For Separate Testsuite and MONK Environment

### ISSUE THREAD

**Issue by erikbgithub** [DFE/MONK#51]
## Problem

The current documentation doesn't tell a user well enough how to integrate MONK in it's test cases and how to work on MONK separately while running their own test suite.
## Solution

A tutorial comparable to #36, but for the user.
## Notes
- Experiences already made by @DMSPeterWinkler and @infeix 
- Changes in Branch `f-userenv-tutorial`

**Comment by sledz** [comment]
This repo will be closed and archived.
